services:
  db:
    image: postgres:16
    volumes:
      - type: bind
        source: ./init.sql
        target: /docker-entrypoint-initdb.d/init.sql
    container_name: db
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${DB_HOST_PORT}:${DB_CONTAINER_PORT}"